### ISSUE TITLE
newer releases not published on packagist

### ISSUE THREAD

**Issue by DRoet** [vmgltd/hlr-lookup-api-php-sdk#16]
Hi.

Just noticed that the newer releases (1.0 and 2.0) are not available on [packagist](https://packagist.org/packages/vmgltd/hlr-lookup-api-php-sdk). The latest version on there is still `v0.0.14`.

Would be nice to have to latest releases on there.

**Comment by marcinxvmg** [comment]
Hey. Sorry to inform you that we stopped supporting packagist releases. We might add them again in the future but currently you'd have to pull in the lib as a drop in as documented here: https://github.com/vmgltd/hlr-lookup-api-php-sdk

**Comment by DRoet** [comment]
Odd choice but thanks for the info!
